### ISSUE TITLE
repositories should contain code, not tarballs of code

### ISSUE THREAD

**Issue by JensTimmerman** [vanhoefm/modwifi#1]
you can just put your code in git and push this to github, 
if you want to make releases, you can click the 'releases' button on github and this will create a tarball from a given branch or tag.

This will really make the workflow op people who want to contribute a lot easyier.

see also https://guides.github.com/activities/hello-world/ and 
https://guides.github.com/introduction/flow/index.html

**Comment by itkovian** [comment]
+1

**Comment by vanhoefm** [comment]
The source code is available, see https://github.com/vanhoefm/modwifi#repositories This repositories compiles/combines the source code of all these repositories (firmware and drivers), and publishes this as a single release, instead of multiple releases on different repositories.

Perhaps this can be described better in the readme? To modify the driver you essentially have to modify our Linux fork, and to modify the firmware you have to modify our fork of the ath9k-htc firmware.
