### ISSUE TITLE
how to set fixed rate?

### ISSUE THREAD

**Issue by eliachen** [vanhoefm/modwifi#2]
you can reference https://github.com/rpp0/open-ath9k-htc-firmware ,and view 
![clipboard](https://cloud.githubusercontent.com/assets/1547622/12416841/d2ab4486-bede-11e5-8b6c-23b61aafa70d.png)

**Comment by eliachen** [comment]
https://github.com/rpp0/open-ath9k-htc-firmware

**Comment by vanhoefm** [comment]
The proper way to do this, is to add a debugfs entry to the driver in https://github.com/vanhoefm/modwifi-linux/blob/research/drivers/net/wireless/ath/ath9k/htc_drv_debug.c which can configure a fixed rate. The firmware is told of the fixed rate using a new WMI command. Otherwise you're forcing a fixed rate for all users.

**Comment by eliachen** [comment]
I have readed <Advanced Wi-Fi Attacks Using Commodity Hardware>,I'm researching the TDMA MAC over the AR9271,I just want to disbale the CSMA/CA,include CTS/RTS,ACK(0),BackOff(0),at the same time,I want a fixed rate. Now,I have the source firmware source,just want to set the register,can you give me some suggestion?
